version: '3.9'

services:
  db:
    container_name: attendance_container
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DB_NAME}
    volumes:
      - 'pg_data:/var/lib/postgresql/data'
    ports:
      - ${PG_PORT}:5432

volumes:
  pg_data:
    driver: local
